version: '3'
services:
  api:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/go/src/github.com/tooth-fairy
    ports: 
      - "2345:2345"
      - "8080:8080"
    environment: 
      ENVIRONMENT: prd
      BIND_ADDR: ":8080"
      DATABASE_USER: olivia 
      DATABASE_PASS: summer@12
      DATABASE_DB: main_test
      DATABASE_HOST: fullstack-postgres
      DATABASE_PORT: 5432
    restart: on-failure
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres
    environment:
      - POSTGRES_DB=main_test
      - POSTGRES_USER=olivia
      - POSTGRES_PASSWORD=summer@12
      - POSTGRES_HOST=fullstack-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # - ./base.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack   

volumes:
  api:
  database_postgres:            

networks:
  fullstack:
    driver: bridge