definitions:
  http.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  patient.Patient:
    properties:
      age:
        type: integer
      created_at:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    required:
    - age
    - email
    - gender
    - name
    - phone
    type: object
info:
  contact: {}
  license: {}
paths:
  /patients:
    get:
      consumes:
      - application/json
      description: get patients
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            Token:
              description: qwerty
              type: string
          schema:
            items:
              $ref: '#/definitions/patient.Patient'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: List patients
swagger: "2.0"
